CREATE TABLE `key_records` (
	`id` text PRIMARY KEY NOT NULL,
	`make` text NOT NULL,
	`model` text NOT NULL,
	`year_from` integer NOT NULL,
	`year_to` integer,
	`car_photo_key` text,
	`oem_key_photo_key` text,
	`universal_key_photo_key` text,
	`transponder_clonable` integer,
	`power_supply_requirement` text,
	`akl_compatible` integer,
	`add_key_compatible` integer,
	`akl_pin_method` text,
	`akl_pin_supplier` text,
	`add_key_pin_method` text,
	`add_key_pin_supplier` text,
	`key_cloning` integer,
	`key_blank_code` text,
	`lishi_in_stock` integer,
	`key_blanks_in_stock` integer,
	`universal_key_compatible` integer,
	`compatible_universal_keys` text,
	`universal_key_in_stock` integer,
	`universal_key_supplier` text,
	`oem_key_in_stock` integer,
	`oem_key_supplier` text,
	`lead_time` text,
	`oem_price_pence` integer,
	`universal_price_pence` integer,
	`notes` text,
	`created_by` text NOT NULL,
	`updated_by` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE INDEX `key_records_vehicle_idx` ON `key_records` (`make`,`model`,`year_from`);--> statement-breakpoint
CREATE INDEX `key_records_updated_at_idx` ON `key_records` (`updated_at`);