export type VehicleMake = {
  name: string;
  aliases?: string[];
  models: string[];
};

// This catalogue powers the picker while live pricing records are added to the
// database. Both fields still accept a typed value when a vehicle is not listed.
export const vehicleCatalogue: VehicleMake[] = [
  { name: "Abarth", models: ["124 Spider", "500", "595", "695"] },
  { name: "Alfa Romeo", aliases: ["Alfa"], models: ["147", "156", "159", "Giulia", "Giulietta", "MiTo", "Stelvio", "Tonale"] },
  { name: "Aston Martin", models: ["DB9", "DB11", "DB12", "DBX", "Vantage"] },
  { name: "Audi", models: ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "TT"] },
  { name: "Bentley", models: ["Bentayga", "Continental", "Flying Spur"] },
  { name: "BMW", aliases: ["B M W"], models: ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "i3", "i4", "iX", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4"] },
  { name: "BYD", models: ["Atto 3", "Dolphin", "Seal", "Seal U"] },
  { name: "Chevrolet", aliases: ["Chevy"], models: ["Aveo", "Captiva", "Cruze", "Kalos", "Matiz", "Orlando", "Spark", "Trax"] },
  { name: "Chrysler", models: ["300C", "Grand Voyager", "PT Cruiser", "Voyager"] },
  { name: "Citroën", aliases: ["Citroen"], models: ["Berlingo", "C1", "C2", "C3", "C3 Aircross", "C4", "C4 Cactus", "C4 Picasso", "C5", "C5 Aircross", "C8", "Dispatch", "DS3", "Nemo", "Relay", "Saxo", "Xsara Picasso"] },
  { name: "Cupra", models: ["Ateca", "Born", "Formentor", "Leon", "Tavascan"] },
  { name: "Dacia", models: ["Duster", "Jogger", "Logan", "Sandero", "Spring"] },
  { name: "Daewoo", models: ["Kalos", "Lanos", "Matiz", "Nubira"] },
  { name: "Daihatsu", models: ["Copen", "Materia", "Sirion", "Terios"] },
  { name: "DS", aliases: ["DS Automobiles"], models: ["DS 3", "DS 4", "DS 5", "DS 7", "DS 9"] },
  { name: "Fiat", models: ["124 Spider", "500", "500L", "500X", "Bravo", "Doblo", "Ducato", "Fiorino", "Grande Punto", "Panda", "Punto", "Scudo", "Tipo"] },
  { name: "Ford", models: ["B-Max", "C-Max", "EcoSport", "Edge", "Escort", "Fiesta", "Focus", "Fusion", "Galaxy", "Ka", "Kuga", "Mondeo", "Mustang", "Puma", "Ranger", "S-Max", "Tourneo", "Transit", "Transit Connect", "Transit Custom"] },
  { name: "Honda", models: ["Accord", "Civic", "CR-V", "e", "FR-V", "HR-V", "Insight", "Jazz", "NSX", "S2000"] },
  { name: "Hyundai", models: ["Bayon", "Coupe", "Getz", "i10", "i20", "i30", "i40", "Ioniq", "Ioniq 5", "Ioniq 6", "Kona", "Santa Fe", "Tucson"] },
  { name: "Infiniti", models: ["EX", "FX", "G", "M", "Q30", "Q50", "Q60", "QX30", "QX50", "QX70"] },
  { name: "Isuzu", models: ["D-Max", "Trooper"] },
  { name: "Jaguar", models: ["E-Pace", "F-Pace", "F-Type", "I-Pace", "S-Type", "XE", "XF", "XJ", "X-Type"] },
  { name: "Jeep", models: ["Avenger", "Cherokee", "Compass", "Grand Cherokee", "Patriot", "Renegade", "Wrangler"] },
  { name: "Kia", models: ["Carens", "Ceed", "EV3", "EV6", "EV9", "Niro", "Optima", "Picanto", "ProCeed", "Rio", "Sorento", "Soul", "Sportage", "Stinger", "Stonic", "Venga"] },
  { name: "KGM", aliases: ["SsangYong", "Ssang Yong"], models: ["Korando", "Musso", "Rexton", "Rodius", "Tivoli", "Torres"] },
  { name: "Land Rover", aliases: ["Range Rover"], models: ["Defender", "Discovery", "Discovery Sport", "Freelander", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"] },
  { name: "Lexus", models: ["CT", "ES", "GS", "IS", "LBX", "LC", "LS", "NX", "RC", "RX", "RZ", "UX"] },
  { name: "Maserati", models: ["Ghibli", "GranTurismo", "Grecale", "Levante", "Quattroporte"] },
  { name: "Mazda", models: ["2", "3", "5", "6", "CX-3", "CX-30", "CX-5", "CX-60", "CX-80", "MX-5", "RX-8"] },
  { name: "Mercedes-Benz", aliases: ["Mercedes", "Merc"], models: ["A-Class", "B-Class", "C-Class", "CLA", "CLC", "CLK", "CLS", "E-Class", "G-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "M-Class", "S-Class", "SL", "SLK", "Sprinter", "V-Class", "Vito"] },
  { name: "MG", aliases: ["M G"], models: ["3", "4", "5", "6", "GS", "HS", "MG3", "MG4", "MG5", "MG ZS", "TF", "ZS"] },
  { name: "MINI", aliases: ["Mini Cooper"], models: ["Clubman", "Convertible", "Cooper", "Countryman", "Hatch", "Paceman"] },
  { name: "Mitsubishi", models: ["ASX", "Colt", "Eclipse Cross", "L200", "Lancer", "Outlander", "Pajero", "Shogun", "Space Star"] },
  { name: "Nissan", models: ["350Z", "370Z", "Almera", "Ariya", "Cube", "Juke", "Leaf", "Micra", "Murano", "Navara", "Note", "Pathfinder", "Primastar", "Pulsar", "Qashqai", "Townstar", "X-Trail"] },
  { name: "Opel", aliases: ["Vauxhall"], models: ["Adam", "Agila", "Ampera", "Antara", "Astra", "Cascada", "Combo", "Corsa", "Crossland", "Frontera", "Grandland", "Insignia", "Meriva", "Mokka", "Movano", "Signum", "Tigra", "Vectra", "Vivaro", "Zafira"] },
  { name: "Peugeot", models: ["1007", "106", "107", "108", "2008", "206", "207", "208", "3008", "306", "307", "308", "4007", "406", "407", "5008", "508", "807", "Bipper", "Boxer", "Expert", "Partner", "RCZ", "Rifter"] },
  { name: "Polestar", models: ["1", "2", "3", "4"] },
  { name: "Porsche", models: ["718", "911", "Boxster", "Cayenne", "Cayman", "Macan", "Panamera", "Taycan"] },
  { name: "Renault", models: ["Arkana", "Austral", "Captur", "Clio", "Espace", "Fluence", "Kadjar", "Kangoo", "Koleos", "Laguna", "Master", "Megane", "Modus", "Scenic", "Trafic", "Twingo", "Zoe"] },
  { name: "Saab", models: ["9-3", "9-5", "900", "9000"] },
  { name: "SEAT", aliases: ["Seat"], models: ["Alhambra", "Altea", "Arona", "Arosa", "Ateca", "Cordoba", "Exeo", "Ibiza", "Leon", "Mii", "Tarraco", "Toledo"] },
  { name: "Škoda", aliases: ["Skoda"], models: ["Citigo", "Elroq", "Enyaq", "Fabia", "Kamiq", "Karoq", "Kodiaq", "Octavia", "Rapid", "Roomster", "Scala", "Superb", "Yeti"] },
  { name: "Smart", models: ["#1", "#3", "Forfour", "Fortwo", "Roadster"] },
  { name: "Subaru", models: ["BRZ", "Forester", "Impreza", "Legacy", "Levorg", "Outback", "Solterra", "Tribeca", "XV"] },
  { name: "Suzuki", models: ["Alto", "Baleno", "Celerio", "Grand Vitara", "Ignis", "Jimny", "S-Cross", "Splash", "Swift", "SX4", "Vitara", "Wagon R"] },
  { name: "Tesla", models: ["Model 3", "Model S", "Model X", "Model Y"] },
  { name: "Toyota", models: ["Auris", "Avensis", "Aygo", "bZ4X", "C-HR", "Camry", "Celica", "Corolla", "GT86", "Hilux", "Land Cruiser", "Prius", "Proace", "RAV4", "Supra", "Verso", "Yaris", "Yaris Cross"] },
  { name: "Vauxhall", aliases: ["Opel"], models: ["Adam", "Agila", "Ampera", "Antara", "Astra", "Cascada", "Combo", "Corsa", "Crossland", "Frontera", "Grandland", "Insignia", "Meriva", "Mokka", "Movano", "Signum", "Tigra", "Vectra", "Vivaro", "Zafira"] },
  { name: "Volkswagen", aliases: ["VW", "V W"], models: ["Amarok", "Arteon", "Beetle", "Bora", "Caddy", "California", "Caravelle", "Crafter", "Eos", "Fox", "Golf", "ID.3", "ID.4", "ID.5", "ID.7", "Jetta", "Passat", "Polo", "Scirocco", "Sharan", "T-Cross", "T-Roc", "Taigo", "Tiguan", "Touareg", "Touran", "Transporter", "Up!"] },
  { name: "Volvo", models: ["C30", "C40", "EX30", "EX40", "EX90", "S40", "S60", "S80", "S90", "V40", "V50", "V60", "V70", "V90", "XC40", "XC60", "XC70", "XC90"] },
].sort((a, b) => a.name.localeCompare(b.name, "en-GB"));
